#pragma config(Sensor, in1,    linefollower1,  sensorLineFollower)
#pragma config(Sensor, in2,    linefollower2,  sensorLineFollower)
#pragma config(Sensor, in3,    linefollower3,  sensorLineFollower)
#pragma config(Motor,  port1,           sol,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           sag,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1==1)
	if(sensorValue)
		if(SensorValue(linefollower1) > 1000)
			{
        // counter-steer right:
        motor[leftMotor]  = 63;
        motor[rightMotor] = 0;
      }
    // CENTER sensor sees dark:
    if(SensorValue(linefollower2) > 1000)
       {
        // go straight
         motor[leftMotor]  = 63;
         motor[rightMotor] = 63;
       }
    // LEFT sensor sees dark:
    if(SensorValue(linefollower3) > 1000)
     {
      // counter-steer left:
      motor[leftMotor]  = 0;
      motor[rightMotor] = 63;
    }
  }
}

}
